### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by tlycken** [timholy/Ratios.jl#4]
Some [Interpolations.jl tests are failing](https://travis-ci.org/tlycken/Interpolations.jl/jobs/80839420) because they need features added in #3. Time for `v0.0.3`, pretty please? :)

**Comment by timholy** [comment]
Sorry about that. See https://github.com/JuliaLang/METADATA.jl/pull/3426. And now you can tag releases, too.

**Comment by tlycken** [comment]
:+1:
